# -*- coding: utf-8 -*-
"""Day_14_Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import numpy as np
import pandas as pd
from scipy.stats import skew

#Create Hospital Waiting Time Data (in minutes)

waiting_time = [10, 15, 20, 12, 18, 25, 30, 45, 50, 8,
                14, 22, 19, 17, 35, 40, 55, 60, 13, 16]

df = pd.DataFrame({
    "Waiting_Time": waiting_time
})

print("Hospital Waiting Time Data:")
print(df)


#Find Variance and Range

variance = df["Waiting_Time"].var()
range_value = df["Waiting_Time"].max() - df["Waiting_Time"].min()

print("\nVariance of Waiting Time:", variance)
print("Range of Waiting Time:", range_value)


#Identify Skewness

skewness_value = skew(df["Waiting_Time"])

print("\nSkewness of Waiting Time:", skewness_value)

if skewness_value > 0:
    print("The distribution is Right Skewed")
elif skewness_value < 0:
    print("The distribution is Left Skewed")
else:
    print("The distribution is Normally Distributed")



#Detect Outliers using IQR

Q1 = df["Waiting_Time"].quantile(0.25)
Q3 = df["Waiting_Time"].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[(df["Waiting_Time"] < lower_limit) |
              (df["Waiting_Time"] > upper_limit)]

print("\nQ1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nOutliers:")
print(outliers)