# -*- coding: utf-8 -*-
"""Day_15_Task_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#exam marks analysis----np.random.normal(loc,std,size)
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

loc = 65
std = 12
size = 150

marks = np.random.normal(loc, std, size)

plt.figure(figsize=(8,5))
plt.hist(marks, bins=20)
plt.title("Exam Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.show()

print("Average Marks:", np.mean(marks))
print("Standard Deviation:", np.std(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))