# -*- coding: utf-8 -*-
"""Day_14_Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import numpy as np
import pandas as pd

#Create 30 Days Sales Data

np.random.seed(10)

sales = np.random.randint(20000, 50000, 30)

df = pd.DataFrame({
    "Day": range(1, 31),
    "Sales": sales
})

print("30 Days Sales Data:")
print(df)



#Calculate Mean, Median, Mode

mean_sales = df["Sales"].mean()
median_sales = df["Sales"].median()
mode_sales = df["Sales"].mode()[0]

print("\nMean Sales:", mean_sales)
print("Median Sales:", median_sales)
print("Mode Sales:", mode_sales)


#Calculate Standard Deviation and Variance

std_sales = df["Sales"].std()
var_sales = df["Sales"].var()

print("\nStandard Deviation:", std_sales)
print("Variance:", var_sales)


#Calculate Correlation

correlation = df["Day"].corr(df["Sales"])

print("\nCorrelation between Day and Sales:", correlation)