# -*- coding: utf-8 -*-
"""Day_15_Task_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#Loan Default Rate
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

size = 200

loan_default = np.random.choice([0, 1], size=size, p=[0.85, 0.15])

default_rate = np.mean(loan_default)

plt.figure(figsize=(6,4))
plt.hist(loan_default, bins=2)
plt.title("Loan Default Distribution")
plt.xlabel("0 = No Default, 1 = Default")
plt.ylabel("Number of Customers")
plt.show()

print("Total Customers:", size)
print("Number of Defaults:", np.sum(loan_default))
print("Default Rate:", default_rate)