# -*- coding: utf-8 -*-
"""Day_15_Task_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#6.temparature variation---use random,no. of days
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 30

temperature = np.random.uniform(20, 38, days)

plt.figure(figsize=(8,5))
plt.plot(temperature)
plt.title("Temperature Variation Over Days")
plt.xlabel("Days")
plt.ylabel("Temperature (°C)")
plt.grid()
plt.show()

print("Average Temperature:", np.mean(temperature))
print("Maximum Temperature:", np.max(temperature))
print("Minimum Temperature:", np.min(temperature))
print("Temperature Standard Deviation:", np.std(temperature))