# -*- coding: utf-8 -*-
"""Day_15_Task_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#10.covid cases growth----np.cumsum(np.random.randint())
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 60

daily_cases = np.random.randint(50, 500, days)
total_cases = np.cumsum(daily_cases)

plt.figure(figsize=(8,5))
plt.plot(total_cases)
plt.title("COVID Cases Growth Over Time")
plt.xlabel("Days")
plt.ylabel("Total Cases")
plt.grid(True)
plt.show()

print("Total Cases After", days, "Days:", total_cases[-1])
print("Average Daily Cases:", np.mean(daily_cases))
print("Maximum Daily Cases:", np.max(daily_cases))
print("Minimum Daily Cases:", np.min(daily_cases))