# -*- coding: utf-8 -*-
"""Day_15_Task_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#employee salary distribution
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

mean = 50000
std = 8000
size = 200

salaries = np.random.normal(mean, std, size)

plt.figure(figsize=(8,5))
plt.hist(salaries, bins=20)
plt.title("Employee Salary Distribution")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.grid(True)
plt.show()

print("Average Salary:", np.mean(salaries))
print("Salary Standard Deviation:", np.std(salaries))
print("Minimum Salary:", np.min(salaries))
print("Maximum Salary:", np.max(salaries))