# -*- coding: utf-8 -*-
"""Day_14_Task_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import pandas as pd
import matplotlib.pyplot as plt


#Create Salary Dataset


salary = [25000, 30000, 35000, 40000, 45000, 50000, 55000,
          60000, 65000, 70000, 75000, 80000, 85000,
          120000, 150000, 200000]

df = pd.DataFrame({"Salary": salary})

print("Salary Dataset:")
print(df)

#Calculate Quartiles

Q1 = df["Salary"].quantile(0.25)
Q2 = df["Salary"].quantile(0.50)
Q3 = df["Salary"].quantile(0.75)

print("\nQuartiles:")
print("Q1 (25%):", Q1)
print("Q2 (Median):", Q2)
print("Q3 (75%):", Q3)

#Plot Boxplot

plt.boxplot(df["Salary"])
plt.title("Salary Distribution")
plt.ylabel("Salary (INR)")
plt.show()

#Interpretation

print("\nInterpretation:")
print("The boxplot shows how salaries are distributed in the company.")
print("If the upper values are far from the main box, it indicates income inequality.")
print("A large gap between Q1 and Q3 shows high salary variation.")
print("Higher salaries at the top indicate that few employees earn much more than others.")