# -*- coding: utf-8 -*-
"""Day_15_Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

start = 200
stop = 800
size = 30

traffic = np.random.randint(start, stop, size)

plt.figure(figsize=(8,5))
plt.plot(traffic)
plt.title("Website Traffic Trend (30 Days)")
plt.xlabel("Days")
plt.ylabel("Number of Visitors")
plt.grid(True)
plt.show()

print("Minimum Traffic:", np.min(traffic))
print("Maximum Traffic:", np.max(traffic))
print("Average Traffic:", np.mean(traffic))
print("Total Visitors in 30 Days:", np.sum(traffic))