# -*- coding: utf-8 -*-
"""Day_15_Task_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#12.eommerce order analysis---np.random.randint
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 30

orders = np.random.randint(100, 1000, days)

plt.figure(figsize=(8,5))
plt.plot(orders)
plt.title("E-commerce Order Analysis (30 Days)")
plt.xlabel("Days")
plt.ylabel("Number of Orders")
plt.grid(True)
plt.show()

print("Total Orders:", np.sum(orders))
print("Average Daily Orders:", np.mean(orders))
print("Maximum Orders in a Day:", np.max(orders))
print("Minimum Orders in a Day:", np.min(orders))