# -*- coding: utf-8 -*-
"""Day_15_Task_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#7.sales forecast vs actual---linspace,np.normal
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 30

forecast = np.linspace(1000, 1500, days)
actual = forecast + np.random.normal(0, 80, days)

plt.figure(figsize=(8,5))
plt.plot(forecast, label="Forecast Sales")
plt.plot(actual, label="Actual Sales")
plt.title("Sales Forecast vs Actual")
plt.xlabel("Days")
plt.ylabel("Sales")
plt.legend()
plt.grid(True)
plt.show()

print("Average Forecast Sales:", np.mean(forecast))
print("Average Actual Sales:", np.mean(actual))
print("Forecast Std Dev:", np.std(forecast))
print("Actual Std Dev:", np.std(actual))