# -*- coding: utf-8 -*-
"""Day_15_Task_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#11.customer churn rate----np.choice
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

customers = 300

churn = np.random.choice([0, 1], size=customers, p=[0.8, 0.2])

churn_rate = np.mean(churn) * 100

plt.figure(figsize=(6,4))
plt.hist(churn, bins=2)
plt.title("Customer Churn Distribution")
plt.xlabel("0 = Retained, 1 = Churned")
plt.ylabel("Number of Customers")
plt.show()

print("Total Customers:", customers)
print("Number of Churned Customers:", np.sum(churn))
print("Churn Rate (%):", churn_rate)