# -*- coding: utf-8 -*-
"""Day_15_Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

mean = 0.5
std = 2
size = 100

stock_price = np.cumsum(np.random.normal(mean, std, size)) + 100

plt.figure(figsize=(8,5))
plt.plot(stock_price)
plt.title("Stock Price Movement using Cumulative Sum")
plt.xlabel("Days")
plt.ylabel("Stock Price")
plt.grid(True)
plt.show()

print("Initial Price:", 100)
print("Final Price:", stock_price[-1])
print("Average Price:", np.mean(stock_price))
print("Price Volatility (Std Dev):", np.std(stock_price))