# -*- coding: utf-8 -*-
"""Day_15_Task_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#9.website conversion rate----vistiors,conversions
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 30

visitors = np.random.randint(500, 2000, days)
conversions = np.random.randint(50, 300, days)

conversion_rate = (conversions / visitors) * 100

plt.figure(figsize=(8,5))
plt.plot(conversion_rate)
plt.title("Website Conversion Rate Over Time")
plt.xlabel("Days")
plt.ylabel("Conversion Rate (%)")
plt.grid(True)
plt.show()

print("Average Visitors:", np.mean(visitors))
print("Average Conversions:", np.mean(conversions))
print("Average Conversion Rate (%):", np.mean(conversion_rate))
print("Maximum Conversion Rate (%):", np.max(conversion_rate))