# -*- coding: utf-8 -*-
"""Day_15_Task_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

#8.inventory stock levels---random.randint
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

days = 30

stock_levels = np.random.randint(50, 300, days)

plt.figure(figsize=(8,5))
plt.plot(stock_levels)
plt.title("Inventory Stock Levels Over Time")
plt.xlabel("Days")
plt.ylabel("Stock Quantity")
plt.grid(True)
plt.show()

print("Average Stock Level:", np.mean(stock_levels))
print("Maximum Stock Level:", np.max(stock_levels))
print("Minimum Stock Level:", np.min(stock_levels))
print("Total Stock Across Days:", np.sum(stock_levels))